spring:
  application:
    name: users

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5439/${POSTGRES_DB}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

server:
  port: 8081